### ISSUE TITLE
[bug] 课程监控功能的 bug

### ISSUE THREAD

**Issue by hebingchang** [clouduan/HelloElectsys#8]
在测试中，课程虽然人数满了，但是监控功能仍然提示选课提交成功并停止监控

**Comment by voldikss** [comment]
dalao 还有课要选么 :neckbeard:

**Comment by hebingchang** [comment]
哈哈没事，只是提个建议，插件还挺好用的
话说回来教学信息服务网换新网站了，有跟进计划吗😏

**Comment by voldikss** [comment]
插件我弄好之后发现自己没什么需求了，而且也没有成功的案例。
一直听说要换，换了之后我有计划好好学学js再跟进。话说每次开放选课都是在考试周，就感觉有点尴尬。

**Comment by Yiyiyimu** [comment]
@voldikss 只能趁着第三轮调试了hhh

**Comment by voldikss** [comment]
@Yiyiyimu 是，很尴尬 😢

**Comment by hebingchang** [comment]
@voldikss 错怪你了，其实是昨天晚上 electsys 爆炸了

**Comment by voldikss** [comment]
@hebingchang 我刚试了下，还真是哈哈
